@startuml Design
skinparam style strictuml

box "Window\nContext"
actor "User" as User
end box

box "XRay"
participant Console [
  =Console
  ----
  content script
]
participant Proxy [
  =Proxy
  ----
  content script
]
end box

box "Firefox Runtime Context"
participant Devtools [
  =Devtools
]
participant Background [
  =Background
]
database Storage
participant Panel [
  =Panel
  ----
  DevTools View
]
end box

User -> Devtools: Open Devtools
Devtools o->o Devtools: Create Panel
User -> Panel: Select Panel

activate Panel
Panel o->o Panel: createApp + mount
Storage -> Panel: read payload
Panel -> Panel: Compare objects
Panel ->o]: Display result
deactivate Panel

Background <- Panel: browser.runtime.connect
activate Background
Background <-- Panel: keep alive

User -> Console: execute\njsdiff.diff(...)
activate Console
  Console -> Proxy: PROGRESS
  activate Proxy
    Proxy -> Background: PROGRESS
  deactivate Proxy
  Console o->o Console: clone arguments
  Console -> Proxy: DIFF
deactivate Console
activate Proxy
Proxy -> Devtools: SAVE
deactivate Proxy

activate Devtools
  Devtools o<->o Devtools: arrange payload
  Devtools -> Storage: write payload
  Devtools --> Background: ERROR
  Devtools -> Background: DIFF
deactivate Devtools

Background -> Panel: port.postMessage

deactivate Background

activate Panel
  Panel -> Panel: Compare objects
  Panel ->o]: Display result
deactivate Panel

User -> Panel: ^+F\n⌘+F

activate Panel
  Panel -> Panel: search in DOM
  Panel ->o]: Display result
deactivate Panel

@enduml
