@startuml
skinparam style strictuml

box "User Window Context"
actor "Users DevTools" as User
participant Console [
  =Console
  ----
  content script
  MAIN world
]
end box
box "Chrome Runtime Context"
participant Proxy [
  =Proxy
  ----
  content script
  ISOLATED world
]
participant Devtools [
  =Devtools
]
database Storage
participant Panel [
  =JSDiff Panel
  ----
  DevTools View
]
end box

User -> Devtools: Open Devtools
Devtools o->o Devtools: Create Panel
User -> Panel: Select Panel

activate Panel
Panel o->o Panel: createApp + mount
Storage -> Panel: read payload
Panel -> Panel: Compare objects
Panel ->o]: Display result
deactivate Panel

User -> Console: execute\nconsole.diff(...)

activate Console
Console -> Proxy: PROGRESS
activate Proxy
Proxy -> Panel: PROGRESS
deactivate Proxy
Console o->o Console: clone arguments
Console -> Proxy: DIFF
deactivate Console
activate Proxy
Proxy -> Devtools: SAVE
deactivate Proxy

activate Devtools
Devtools o<->o Devtools: arrange payload
Devtools -> Storage: write payload
Devtools --> Panel: ERROR
Devtools -> Panel: DIFF
deactivate Devtools

activate Panel
Panel -> Panel: Compare objects
Panel ->o]: Display result
deactivate Panel

User -> Panel: ^+F\n⌘+F

activate Panel
Panel -> Panel: Search in DOM
Panel ->o]: Display result
deactivate Panel
@enduml
