@startuml Design
skinparam style strictuml

box "Window Context"
actor "User" as User
participant Console [
  =Console
  ----
  content script
  MAIN world
]
end box
box "Chrome Runtime Context"
participant Proxy [
  =Proxy
  ----
  content script
  ISOLATED world
]
participant Devtools [
  =Devtools
]
database Storage
participant Panel [
  =JSDiff Panel
  ----
  DevTools View
]
end box

User -> Devtools: Open Devtools
rnote over Devtools: Create Panel
User -> Panel: Select Panel

activate Panel
rnote over Panel: createApp\nand mount
Storage -> Panel: read payload
rnote over Panel: Compare objects
rnote over Panel: Display diff
deactivate Panel

User -> Console: execute\nconsole.diff(...)

activate Console
  Console -> Proxy: CS_PROGRESS
  activate Proxy
  Proxy -> Panel: RT_PROGRESS
  deactivate Proxy

  rnote over Console: clone arguments
  Console -> Proxy: CS_DIFF
deactivate Console

activate Proxy
Proxy -> Devtools: RT_SAVE
deactivate Proxy

activate Devtools
rnote over Devtools: arrange payload
Devtools -> Storage: write payload
Devtools -> Panel: RT_DIFF
rnote over Panel: Compare objects
rnote over Panel: Display diff
Devtools --> Panel: RT_ERROR
deactivate Devtools

User -> Panel: ^+F\n⌘+F
rnote over Panel: Search in DOM
rnote over Panel: Alter DOM

@enduml
