@startuml Design
skinparam style strictuml

box "Window\nContext"
actor "User" as User
end box

box "XRay"
participant Console [
  =Console
  ----
  ""content script""
]
participant Proxy [
  =Proxy
  ----
  ""content script""
]
end box

box "Firefox Runtime Context"
participant Background [
  =Background
]
participant Devtools [
  =Devtools
]
database Storage
participant Panel [
  =JSDiff Panel
  ----
  ""DevTools View""
]
end box

User -> Devtools: Open Devtools
activate Devtools
  rnote over Devtools: Create Panel
  Devtools -> Background: browser.runtime.connect
deactivate Devtools
activate Background

User -> Panel: Select Panel
activate Panel
  rnote over Panel: createApp\nand mount
  Storage -> Panel: read payload
  rnote over Panel: Compare objects
  rnote over Panel: Display diff
  Background <- Panel: browser.runtime.connect
deactivate Panel

User -> Console: execute\njsdiff.diff(...)
activate Console
  Console -> Proxy: CS_PROGRESS
  activate Proxy
    Proxy -> Background: RT_PROGRESS
  deactivate Proxy
  Background -> Panel: RT_PROGRESS
  rnote over Console: clone arguments
  Console -> Proxy: CS_DIFF
deactivate Console
activate Proxy
  Proxy -> Background: RT_SAVE
deactivate Proxy


Background -> Devtools: RT_SAVE
activate Devtools
  rnote over Devtools: arrange payload
  Devtools -> Storage: write payload
  Devtools -> Background: RT_DIFF
  Devtools --> Background: RT_ERROR
deactivate Devtools

Background --> Panel: RT_ERROR
Background -> Panel: RT_DIFF
deactivate Background

rnote over Panel: Compare objects
rnote over Panel: Display diff

User -> Panel: ^+F\n⌘+F
rnote over Panel: Search in DOM
rnote over Panel: Alter DOM

@enduml
