@startuml Design
skinparam style strictuml

box "User's Window Context"
actor "User's\nDevTools" as User
participant Console [
  =Console
  ----
  content script
  MAIN world
]
end box
box "Chrome Runtime Context"
participant Proxy [
  =Proxy
  ----
  content script
  ISOLATED world
]
database Storage
participant Panel [
  =JSDiff Panel
  ----
  DevTools View
]
end box

[-> User: Open Devtools
=== Invoke API ==

User -> Console: console.diff(...)

activate Console
Console -> Proxy: jsdiff-console-to-proxy-inprogress
activate Proxy
  Proxy -> Panel: jsdiff-proxy-to-panel-inprogress
deactivate Proxy
Console o->o Console: clone arguments
Console -> Proxy: jsdiff-console-to-proxy-compare
deactivate Console

activate Proxy
Proxy o<->o Proxy: arrange payload
Proxy -> Storage: write payload
Proxy --> Panel: jsdiff-proxy-to-panel-error
Proxy -> Panel: jsdiff-proxy-to-panel-compare
deactivate Proxy

activate Panel
Storage -> Panel: read payload
Panel -> Panel: Compare objects
Panel ->o]: Display result
deactivate Panel

=== Search in DevTools Panel ==
[-> User: ctrl+F\ncmd+F
User -> Panel: jsdiff-devtools-to-panel-search
activate Panel
Panel -> Panel: search in DOM
Panel ->o]: Display result
deactivate Panel

@enduml
