export const TAG = {
  EMPTY: '(empty)',
  UNDEFINED: '(undefined)',
  NULL: '(null)',
  NATIVE_FUNCTION: '𝑓(native)',
  EXCEPTION_FALLBACK: '⁉️(exception)',
  EXCEPTION: (str: string) => `⁉️(${str})`,
  RECURRING_ARRAY: (id: string) => `0x${id}: [♻️]`,
  RECURRING_OBJECT: (id: string) => `0x${id}: {♻️}`,
  RECURRING_SET: (id: string) => `0x${id}: Set[♻️]`,
  RECURRING_MAP: (id: string) => `0x${id}: Map{♻️}`,
  NON_SERIALIZABLE: (id: string) => `0x${id}: unserializable`,
  SYMBOL: (name: string, id: string) => `0x${id}: ${name}`,
  FUCNTION: (hash: string) => `𝑓(${hash})`,
};
